### ISSUE TITLE
Show Brightness for mouse in -l output

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [LoLei/razer-cli#43]
Not all hardware has a generic brightness, but that is no excuse to not show what it is set to
```
def list_devices(device_manager):
    """
    List all connected Razer devices
    https://github.com/openrazer/openrazer/blob/master/examples/list_devices.py
    """

    print("Found {} Razer devices".format(len(device_manager.devices)))

    # Iterate over each device and pretty out some standard information about each
    for device in device_manager.devices:
        print("{}:".format(device.name))
        print("   type: {}".format(device.type))
        if (device.type == "mouse"):
            print("   DPI: {}".format(device.dpi))
            print("   max DPI: {}".format(device.max_dpi))
        if device.capabilities['poll_rate']:
            print("   polling rate: {}".format(device.poll_rate))
        if device.capabilities['brightness']:
            print("   brightness: {}".format(device.brightness))
        if device.capabilities['lighting_logo_brightness']:
            print("   brightness (logo): {}".format(device.fx.misc.logo.brightness))
        if device.capabilities['lighting_scroll_brightness']:
            print("   brightness (wheel): {}".format(device.fx.misc.scroll_wheel.brightness))
        if device.capabilities['lighting_left_brightness']:
            print("   brightness (left): {}".format(device.fx.misc.left.brightness))
        if device.capabilities['lighting_right_brightness']:
            print("   brightness (right): {}".format(device.fx.misc.right.brightness))
        print("   serial: {}".format(device.serial))
        print("   firmware version: {}".format(device.firmware_version))
        print("   driver version: {}".format(device.driver_version))

        device_effects = get_effects_of_device(device)
        print("   effects: {}".format(device_effects))

        if (args.list_devices_long):
            print("   capabilities: {}".format(device.capabilities))
        elif (args.list_devices_long_human):
            print("   capabilities:")
            for i in device.capabilities:
                print("      ", i, "=", device.capabilities[i])
    print()
```
To Do: add support to set brightness to individual parts of device

**Comment by GM-Script-Writer-62850** [comment]
Attempt support for setting different brightness for different parts of devices
[razer_cli_expermental.py.zip](https://github.com/LoLei/razer-cli/files/5844833/razer_cli_expermental.py.zip)
Testing shows it works for me, but i feel it needs a bit of cleanup, just looks way too messy for my taste, should be a better way

**Comment by LoLei** [comment]
While you're at it, you could replace the `device.capabilities[key]` calls with `device.capabilities.get(key)`, as it might result in a `KeyError` if the dictionary doesn't have that key. Even though it seems openrazer has all keys set for all devices, better safe than sorry?

**Comment by GM-Script-Writer-62850** [comment]
Is that not the entire purpose of the `device.capabilities` object?

**Comment by LoLei** [comment]
I haven't looked into it. I don't really care, just a suggestion.

**Comment by GM-Script-Writer-62850** [comment]
it is not a big deal to me, i do not use rgb at all, i just noticed the lack of a feature while looking over some of the code and felt like making it for no other reason, it is a cli application it should have decent functionality at the very least

the only piece of rbg software i run is msi-rgb (depreciated) and i only use it to disable the rgb on my motherboard and this mouse seems to not forget it is set to off and that is all i care about

**Comment by LoLei** [comment]
Regarding this:
>To Do: add support to set brightness to individual parts of device

Is this something still to be done?

**Comment by GM-Script-Writer-62850** [comment]
that is in [comment 2](https://github.com/LoLei/razer-cli/issues/43#issuecomment-763882786) in here, attached

**Comment by GM-Script-Writer-62850** [comment]
[brightness_patch_files.zip](https://github.com/LoLei/razer-cli/files/5861109/brightness_patch_files.zip)
here are some cleaned up files based on the current version
read_support.patch should be safe to fully commit, adding write support is another matter (works, but not happy with it)
razer_cli.py + read_supprt.patch = read support (good to go)
razer_cli.py + read_supprt.patch + write_support.patch = read/write support (ugly messy, should be a better way, but it does work for me)

**Comment by LoLei** [comment]
Alright then let's add the read support first for now, maybe a better way can be found for the write support later.

But I'm getting a `KeyError` on my keyboard due to the `poll_rate` change I believe:
```python
$ razer-cli -l
Found 2 Razer devices
Razer Lancehead Tournament Edition:
   type: mouse
   DPI: (1800, 1800)
   max DPI: 16000
   polling rate: 500
   brightness (logo): 100.0
   brightness (wheel): 100.0
   brightness (left): 100.0
   right brightness: 100.0
   serial: PM1810H05600154
   firmware version: v1.2
   driver version: 2.9.0
   effects: ['left_breath_single', 'left_reactive', 'left_static', 'logo_breath_single', 'logo_reactive', 'logo_static', 'right_breath_single', 'right_reactive', 'right_static', 'scroll_breath_single', 'scroll_reactive', 'scroll_static']
Razer BlackWidow X Chroma Tournament Edition:
   type: keyboard
Traceback (most recent call last):
  File "/home/me/.local/bin/razer-cli", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.9/site-packages/razer_cli/razer_cli.py", line 441, in main
    list_devices(device_manager)
  File "/home/me/.local/lib/python3.9/site-packages/razer_cli/razer_cli.py", line 103, in list_devices
    if device.capabilities['poll_rate']:
KeyError: 'poll_rate'
```

Is there a reason you changed it?
```diff
-        if device.has("poll_rate"):
+        if device.capabilities['poll_rate']:
```

**Comment by GM-Script-Writer-62850** [comment]
changed it for consistency, does this work for you?
```
def list_devices(device_manager):
    """
    List all connected Razer devices
    https://github.com/openrazer/openrazer/blob/master/examples/list_devices.py
    """

    print("Found {} Razer devices".format(len(device_manager.devices)))

    # Iterate over each device and pretty out some standard information about each
    for device in device_manager.devices:
        print("{}:".format(device.name))
        print("   type: {}".format(device.type))
        if device.has('dpi'):
            print("   DPI: {}".format(device.dpi))
        if device.has('max_dpi'):
            print("   max DPI: {}".format(device.max_dpi))
        if device.has('poll_rate'):
            print("   polling rate: {}".format(device.poll_rate))
        if device.has('brightness'):
            print("   brightness: {}".format(device.brightness))
        if device.has('lighting_logo_brightness'):
            print("   brightness (logo): {}".format(device.fx.misc.logo.brightness))
        if device.has('lighting_scroll_brightness'):
            print("   brightness (wheel): {}".format(device.fx.misc.scroll_wheel.brightness))
        if device.has('lighting_left_brightness'):
            print("   brightness (left): {}".format(device.fx.misc.left.brightness))
        if device.has('lighting_right_brightness'):
            print("   brightness (right): {}".format(device.fx.misc.right.brightness))
        print("   serial: {}".format(device.serial))
        print("   firmware version: {}".format(device.firmware_version))
        print("   driver version: {}".format(device.driver_version))

        device_effects = get_effects_of_device(device)
        print("   effects: {}".format(device_effects))

        if (args.list_devices_long):
            print("   capabilities: {}".format(device.capabilities))
        elif (args.list_devices_long_human):
            print("   capabilities:")
            for i in device.capabilities:
                print("      ", i, "=", device.capabilities[i])
    print()
```
```
--- razer_cli.py	2021-01-23 16:14:36.879359411 -0500
+++ razer_cli_read_brightness.py	2021-01-24 10:22:53.553176662 -0500
@@ -76,9 +76,7 @@
 
     if args.verbose:
         print("RBG: ")
-        sys.stdout.write(str(r) + " ")
-        sys.stdout.write(str(g) + " ")
-        sys.stdout.write(str(b) + "\n")
+        print(r, g, b)
 
     return [r, g, b]
 
@@ -99,13 +97,22 @@
     for device in device_manager.devices:
         print("{}:".format(device.name))
         print("   type: {}".format(device.type))
-        if (device.type == "mouse"):
+        if device.has('dpi'):
             print("   DPI: {}".format(device.dpi))
+        if device.has('max_dpi'):
             print("   max DPI: {}".format(device.max_dpi))
-        if device.has("poll_rate"):
+        if device.has('poll_rate'):
             print("   polling rate: {}".format(device.poll_rate))
-        if device.capabilities['brightness']:
+        if device.has('brightness'):
             print("   brightness: {}".format(device.brightness))
+        if device.has('lighting_logo_brightness'):
+            print("   brightness (logo): {}".format(device.fx.misc.logo.brightness))
+        if device.has('lighting_scroll_brightness'):
+            print("   brightness (wheel): {}".format(device.fx.misc.scroll_wheel.brightness))
+        if device.has('lighting_left_brightness'):
+            print("   brightness (left): {}".format(device.fx.misc.left.brightness))
+        if device.has('lighting_right_brightness'):
+            print("   brightness (right): {}".format(device.fx.misc.right.brightness))
         print("   serial: {}".format(device.serial))
         print("   firmware version: {}".format(device.firmware_version))
         print("   driver version: {}".format(device.driver_version))
```

**Comment by GM-Script-Writer-62850** [comment]
happen to have a device that supports `available_dpi` or `battery`?
```
def list_devices(device_manager):
    """
    List all connected Razer devices
    https://github.com/openrazer/openrazer/blob/master/examples/list_devices.py
    """

    print("Found {} Razer devices".format(len(device_manager.devices)))

    # Iterate over each device and pretty out some standard information about each
    for device in device_manager.devices:
        print("{}:".format(device.name))
        print("   type: {}".format(device.type))
        if device.has('dpi'):
            print("   DPI: {}".format(device.dpi))
            print("   max DPI: {}".format(device.max_dpi))
            if(device.has('available_dpi')):
                print("   available DPI: {}".format(device.available_dpi))
        if device.has('poll_rate'):
            print("   polling rate: {}".format(device.poll_rate))
        if device.has('battery'):
            print("   battery: {}".format(device.battery))
        if device.has('brightness'):
            print("   brightness: {}".format(device.brightness))
        if device.has('lighting_logo_brightness'):
            print("   brightness (logo): {}".format(device.fx.misc.logo.brightness))
        if device.has('lighting_scroll_brightness'):
            print("   brightness (wheel): {}".format(device.fx.misc.scroll_wheel.brightness))
        if device.has('lighting_left_brightness'):
            print("   brightness (left): {}".format(device.fx.misc.left.brightness))
        if device.has('lighting_right_brightness'):
            print("   brightness (right): {}".format(device.fx.misc.right.brightness))
        print("   serial: {}".format(device.serial))
        print("   firmware version: {}".format(device.firmware_version))
        print("   driver version: {}".format(device.driver_version))

        device_effects = get_effects_of_device(device)
        print("   effects: {}".format(device_effects))

        if (args.list_devices_long):
            print("   capabilities: {}".format(device.capabilities))
        elif (args.list_devices_long_human):
            print("   capabilities:")
            for i in device.capabilities:
                print("      ", i, "=", device.capabilities[i])
    print()
```

**Comment by GM-Script-Writer-62850** [comment]
[Brightness_patch.zip](https://github.com/LoLei/razer-cli/files/5862942/Brightness_patch.zip)
* Assume nothing for `-l` if you can test for it then test for it
* `-l` theoretically supports battery and available_dpi (I lack the hardware to verify if it works)
* Use `has()` for everything
* Overhaul write patch, needs testing but should be hard to break
  - Theoretically supports `lighting_*_brightness` (unless something is added the way they did `scroll_wheel` it will not need a update to support new lighting zones in the future)
* Help message for `-b` option will need a update
  - See lines 480 - 485 of `razer_cli_read+write_brightness.py` for examples

**Comment by LoLei** [comment]
Done in #47
