### ISSUE TITLE
openrazer.client.DaemonNotFound: Could not connect to daemon

### ISSUE THREAD

**Issue by chrisJuresh** [LoLei/razer-cli#67]
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.razer': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/openrazer/client/__init__.py", line 22, in __init__
    self._dbus = session_bus.get_object("org.razer", "/org/razer")
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/razer-cli", line 33, in <module>
    sys.exit(load_entry_point('razer-cli==2.0.1', 'console_scripts', 'razer-cli')())
  File "/usr/lib/python3.9/site-packages/razer_cli-2.0.1-py3.9.egg/razer_cli/razer_cli/main.py", line 27, in main
    device_manager = DeviceManager()
  File "/usr/lib/python3.9/site-packages/openrazer/client/__init__.py", line 24, in __init__
    raise DaemonNotFound("Could not connect to daemon")
openrazer.client.DaemonNotFound: Could not connect to daemon
```
Im on Artix (Arch with runit)

**Comment by LoLei** [comment]
Have you installed  the openrazer daemon and is it running? And added your user to the plugdev group?

I don't know how it works on Artix, but here's the Arch Wiki entry: https://wiki.archlinux.org/title/Razer_peripherals#OpenRazer
