### ISSUE TITLE
Cannot list devices due to getLowBatteryThreshold not being a valid method

### ISSUE THREAD

**Issue by lipovac** [LoLei/razer-cli#70]
[llipovac@llipovac-DT Downloads]$ razer-cli -l
Found 2 Razer device(s)
Razer Basilisk Ultimate (Receiver):
   type: mouse
   DPI: (2500, 2500)
   max DPI: 20000
   polling rate: 500
   battery:
      charge: 97
      charging: False
Traceback (most recent call last):
  File "/home/llipovac/.local/bin/razer-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/llipovac/.local/lib/python3.11/site-packages/razer_cli/razer_cli/main.py", line 30, in main
    rc.run()
  File "/home/llipovac/.local/lib/python3.11/site-packages/razer_cli/razer_cli/rc.py", line 73, in run
    self.device_lister.list()
  File "/home/llipovac/.local/lib/python3.11/site-packages/razer_cli/razer_cli/lister/device_lister.py", line 50, in list
    device.get_low_battery_threshold(), '%')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/openrazer/client/devices/__init__.py", line 494, in get_low_battery_threshold
    return int(self._dbus_interfaces['power'].getLowBatteryThreshold())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/dbus/service.py", line 659, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/service.py", line 249, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getLowBatteryThreshold is not a valid method of interface razer.device.power

**Comment by sk8ersteve** [comment]
I see the same issue with my Razer Viper Ultimate (Wireless)

**Comment by sk8ersteve** [comment]
Looks like an upstream issue. openrazer does not support this method for Razer Viper Ultimate (Wireless) despite having other battery methods:
https://github.com/openrazer/openrazer/blob/43b4a605e84f7530d8763a804eb875936e7bd5d7/daemon/openrazer_daemon/hardware/mouse.py#L882
Same for the Basilisk Ultimate:
https://github.com/openrazer/openrazer/blob/43b4a605e84f7530d8763a804eb875936e7bd5d7/daemon/openrazer_daemon/hardware/mouse.py#L1180

**Comment by LoLei** [comment]
Fixed with https://github.com/LoLei/razer-cli/pull/71

To be in the next release
