### ISSUE TITLE
JSON Decoder error

### ISSUE THREAD

**Issue by miguelcarcamov** [LoLei/razer-cli#75]
Hi,
From some days ago I have been receiving an error after running `razer-cli -e multicolor,xpalette --sync`.
The error that shows up is:
```
Traceback (most recent call last):
  File "/home/miguel/.local/bin/razer-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/miguel/.local/lib/python3.11/site-packages/razer_cli/razer_cli/main.py", line 30, in main
    rc.run()
  File "/home/miguel/.local/lib/python3.11/site-packages/razer_cli/razer_cli/rc.py", line 55, in run
    self.color_effect_handler.handle()
  File "/home/miguel/.local/lib/python3.11/site-packages/razer_cli/razer_cli/handler/color_effect_handler.py", line 31, in handle
    self.setter.set(effects=effects, color=color, zones=zones)
  File "/home/miguel/.local/lib/python3.11/site-packages/razer_cli/razer_cli/setter/color_effect_setter.py", line 21, in set
    self.set_effect_to_device(device, **kwargs)
  File "/home/miguel/.local/lib/python3.11/site-packages/razer_cli/razer_cli/setter/color_effect_setter.py", line 273, in set_effect_to_device
    util.write_settings_to_file(device, effects, color, zones=zones)
  File "/home/miguel/.local/lib/python3.11/site-packages/razer_cli/razer_cli/util.py", line 190, in write_settings_to_file
    json_data = json.load(file)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I'm trying to debug the error without any success. I'm on Manjaro Linux x86_64 with kernel 6.5.0-1-MANJARO

Cheers,

**Comment by Ce1er** [comment]
I was having the same issue with the same error message and it was because of an extra ] at the end of `~/.cache/razer-cli/razer-cli-settings.json`. I removed it and everything works fine, I've been unable to find a way to reproduce that issue so I'm not sure what caused it. I tried running `python /usr/lib/python3.13/site-packages/razer_cli/tests/test_util.py` and one of those tests fails which seems to be related to writing to that file. Both removing the problematic bracket and just deleting the json file worked in solving it for me. So `rm ~/.cache/razer-cli/*` is a quick and easy fix for it.
```
..Adding new settings entry
F..
======================================================================
FAIL: test_write_settings_to_file (__main__.TestUtil.test_write_settings_to_file)
> Test if cache file writing works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/razer_cli/tests/test_util.py", line 41, in test_write_settings_to_file
    self.assertEqual(data["device_name"], "test_device")
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'Razer BlackWidow V4 Pro' != 'test_device'
- Razer BlackWidow V4 Pro
+ test_device


----------------------------------------------------------------------
Ran 5 tests in 0.045s

FAILED (failures=1)
```
So maybe there's something wrong there but I've not seen any issues in using razer-cli since I removed that bracket. And I tried reinstalling to see if it was just a problem when it was freshly installed but I didn't have issues there either.

```
razer-cli: 2.2.1
   Installed in: /usr/lib/python3.13/site-packages/razer_cli
python3-openrazer: 3.10.0
openrazer-daemon: 3.10.0
Python: 3.13.3
```

Installed from gentoo's repos. The only change it makes to the source is this:
```
--- a/setup.py
+++ b/setup.py
@@ -20,6 +20,4 @@ setup(
     packages=find_packages(),
     entry_points={"console_scripts": ["razer-cli=razer_cli.razer_cli.main:main"]},
     python_requires=">=3.6",
-    package_data={'': ['razer_cli/razer_cli/man_pages']},
-    include_package_data=True,
     )
```
